### ISSUE TITLE
Enhance Documentation for variables that are used in several places

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#124]
When `m_flow` is requested, is this the system mass flow rate or the mass flow rate per borehole desired?

I know that the variable `m_flow` is used in many places and maybe we don't want as detailed a description there, but what would you think about having a  `nomenclature` page that describes the variables used in _pygfunction_ and their associated meaning?

Maybe a table similar to [this](http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function)?

**Comment by j-c-cook** [comment]
The mass flow rate `m_flow` is on a per borehole basis.

**Comment by MassimoCimmino** [comment]
@j-c-cook This is a very good point. The variable `m_flow` should always be the total mass flow rate and its current definition depends on the context :

- In the `pipes` module, `m_flow` corresponds to the total flow into the borehole (which would then be divided by the number of parallel U-tubes).
- In the `network` module, `m_flow` corresponds to the total network flow (which would then be divided by the number of parallel branches).

I agree this can get confusing. We can also consider changing the parameter names to better reflect their meaning, perhaps `m_flow_borehole` and `m_flow_network`?

**Comment by j-c-cook** [comment]
Okay thanks I'm glad you think so. 

- I believe the only time in the `pipes` module that the flow is not in series is when there are multiple u-tubes. In that case, the mass flow rate input should be `m_flow / n_tubes`. Where `n_tubes=1` when single, and `n_tubes=2` when double, etc.  
- I'm not as familiar with the `network` module, as I think it may be relatively new. 

I think defining when it is `m_flow_borehole` and `m_flow_network` will make things clear.

**Comment by MassimoCimmino** [comment]
To clarify (unless I misunderstand your comment), when using parallel U-tubes, `m_flow` is still the total flow rate into the borehole and is processed internally by the `pipe` object:
https://github.com/MassimoCimmino/pygfunction/blob/6cf6ada6c3d4d59e8fe63ca7466daba7cae935a4/pygfunction/pipes.py#L1552-L1553

These change are required. Even I have to double-check the input definitions every time I use the models.
