### ISSUE TITLE
Approximation of the finite line source

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#138]
This issue is to implement the approximation of the finite line source solution introduced in [[1]](https://www.sciencedirect.com/science/article/pii/S0735193321003894). An option will be added to choose to evaluate the FLS using the current quadrature method or the approximation.

--------------

[1] Cimmino, M., 2021. An approximation of the finite line source solution to model thermal interactions between geothermal boreholes. _International Communications in Heat and Mass Transfer_, 127, p.105496.

**Comment by j-c-cook** [comment]
Would it be possible to get this into `master` for the `v2.1.0` release? Given that Cimmino (1) mentions a 1000x speed increase, this should provide a nice increase to calculating g-functions with _accuracy_. 

I'd be happy to help make this happen. If you'd want to open a draft PR, I can work on it.

**Comment by MassimoCimmino** [comment]
## `equivalent` solver : Rectangular fields up to 400 boreholes
Results labeled with `'PR-189'` use the approximation of the FLS.

![Figure_1](https://user-images.githubusercontent.com/23085996/149000464-fedbc679-83e8-4171-b73c-a3e0177d6317.png)

![Figure_2](https://user-images.githubusercontent.com/23085996/149000478-e2564b78-7f0f-4267-b641-ecba4f950fff.png)

![Figure_3](https://user-images.githubusercontent.com/23085996/149000483-e1aa56c2-1ba8-4736-a681-2337ee70d567.png)

**Comment by MassimoCimmino** [comment]
## `similarities` solver : Rectangular fields up to 400 boreholes
Results labeled with `'PR-189'` use the approximation of the FLS and `nFLS=10` terms. We can see that the calculation time is only decreased for smaller bore fields.

![Figure_1b](https://user-images.githubusercontent.com/23085996/149051656-66cbbcdb-034d-44b0-8924-e1078b1b4278.png)

![Figure_2b](https://user-images.githubusercontent.com/23085996/149051659-a3c0583a-f3ad-4b2b-996b-e55d931732f6.png)

![Figure_3b](https://user-images.githubusercontent.com/23085996/149051663-c376cfcf-1c10-44d5-9e70-6e3a769c6a39.png)
