### ISSUE TITLE
Requirements not aligned with Python versions

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#139]
Pygfunction-2.0.0 has a `scipy>=1.6.2` requirement. The minimum allowable Python version in that scipy release was Python 3.7 https://pypi.org/project/scipy/1.6.2/.

**Comment by MassimoCimmino** [comment]
@j-c-cook Great catch.

Do you see a need to release a fix quickly for this? I can always update the requirement to Python 3.7 and release a `v2.0.1` hotfix.

If not, I will tag it for `v2.1`. I will revise the milestones for `v2.1` soon and move a few issues to `v2.2`.

**Comment by j-c-cook** [comment]
Given that there is an adequate reason to be using `scipy>=1.6.2`, there are adequate [changes](https://github.com/MassimoCimmino/pygfunction/blob/master/CHANGELOG.md#current-version) to go ahead and wrap up a `v2.1`. 

However, if we can backtrack to a `scipy` version that is compatible with `python==3.6` and maintain the integrity of `pygfunction==2.0`, then I'd advocate a `v2.0.1` hotfix.

**Comment by MassimoCimmino** [comment]
My proposal is to align with the [Anaconda distribution](https://docs.anaconda.com/anaconda/packages/pkg-docs/).

For the Python 3.8 release :

- numpy 1.20.1
- scipy 1.6.2
- matplotlib 3.3.4
- numpydoc 1.1.0
- sphinx 4.0.1

The latest Coolprop release is still 6.4.1.

**Comment by j-c-cook** [comment]
Did you mean to propose 3.8? I tend to not like the idea of going to another version, unless there is a reason. I agree with moving from 3.6->3.7 from pygfunction-v1.x -> pygfunction-2.x respectively for the new additions to scipy that are being used. 

Looking at the same documentation, but for the Python 3.7 release:
- numpy 1.20.1
- scipy 1.6.2
- matplotlib 3.3.4
- numpydoc 1.1.0
- sphinx 4.0.1

**Comment by MassimoCimmino** [comment]
I agree with going for Python 3.7. It seems the versions are the same anyways.

**Comment by MassimoCimmino** [comment]
Looking now further into this issue, it seems the requirements was only incorrect in the README.md file:
https://github.com/MassimoCimmino/pygfunction/blob/0e67d4edbac0df97d4402163ed1e639d33cce588/README.md#L44-L54

The setup.py file correctly shows:
https://github.com/MassimoCimmino/pygfunction/blob/0e67d4edbac0df97d4402163ed1e639d33cce588/setup.py#L9-L18
https://github.com/MassimoCimmino/pygfunction/blob/0e67d4edbac0df97d4402163ed1e639d33cce588/setup.py#L37

**Comment by j-c-cook** [comment]
Looks like you're right. I had seen it on [PyPI](https://pypi.org/project/pygfunction/), and it does look like it was only the README.
