### ISSUE TITLE
Pipe and fluid thermal resistances

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#140]
I noticed that for single and double U-tubes you have the same equation for computing pipe and fluid thermal resistances:

https://github.com/MassimoCimmino/pygfunction/blob/7d37b8b3bf4b349701681e42281c21cccb54ca42/pygfunction/examples/fluid_temperature_multiple_boreholes.py#L86-L94

The `R_f = 1.0/(h_f*2*pi*r_in)` is specifically what I am referring to. 

This is the fluid resistance of a single tube. Is this because your `pipe` objects are setup to receive the fluid to outer pipe wall thermal resistance (`R_fp`) of a single tube?

**Comment by MassimoCimmino** [comment]
I am not sure I fully understand.

`R_f` is the resistance between the fluid and the inner surface of a pipe. `R_fp` is the total resistance between the fluid and the outer surface, which combines the convective (`R_f`) and conductive (`R_p`) resistances. The same resistance is applied to each pipe of each U-tube.

**Comment by j-c-cook** [comment]
That answers my question, thank you. You apply `R_fp` to each tube during calculations. 

This may need adjusted to implement `Coaxial`, but I'm not sure.
