### ISSUE TITLE
NewFeature Local borehole thermal resistance

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#148]
Is the local borehole thermal resistance computed and stored anywhere inside of the `pipe` objects?

**Comment by MassimoCimmino** [comment]
It is not computed or stored, since there is currently no use for it in the `pipes` module.

It could easily be evaluated at the initialization of pipe objects after the calculation of the `_Rd` matrix.

**Comment by j-c-cook** [comment]
I might need it for design purposes, and it would also be nice to have it as a reference point. Are you okay with adding a function that computes the local borehole resistance given a pipe object, mass flow rate and fluid?

**Comment by MassimoCimmino** [comment]
I see an opportunity for a new feature with this issue.

We could add a `update_thermal_resistance()` method to the `pipe` classes, which would build the thermal resistance matrix, initialize stored coefficients (like it is done in the `__init__` methods) and return `R_b`. This adds the possibility to have time-varying resistances during simulations.

A prototype implementation for the `SingleUTube` class:
```
def update_thermal_resistance(self, R_fp)
    # Delta-circuit thermal resistances
    self._Rd = thermal_resistances(
        self.pos, self.r_out, self.b.r_b, self.k_s, self.k_g, R_fp, J=self.J)[1]
    self.R_fp = R_fp

    # Initialize stored_coefficients
    self._initialize_stored_coefficients()

    # Evaluate borehole thermal resistance
    R_b = 1 / np.trace(1 / self._Rd)
    return R_b
```

**Comment by j-c-cook** [comment]
I can concur, there is a need for an `update_thermal_resistance()` method.
