### ISSUE TITLE
Occasional runtime warning

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#155]
I occasionally get the following run time warning. 

```
H:\Masters\ghedt\ghedt\PLAT\pygfunction\pipes.py:736: RuntimeWarning: invalid value encountered in subtract
  if (np.all(np.abs(m_flow_borehole*cp_f - stored_m_flow_cp) < np.abs(stored_m_flow_cp)*tol)
H:\Masters\ghedt\ghedt\PLAT\pygfunction\pipes.py:736: RuntimeWarning: invalid value encountered in multiply
  if (np.all(np.abs(m_flow_borehole*cp_f - stored_m_flow_cp) < np.abs(stored_m_flow_cp)*tol)
```

**Comment by MassimoCimmino** [comment]
@j-c-cook Please let me know if the changes on the development branch [`issue155[...]`](https://github.com/MassimoCimmino/pygfunction/tree/issue155_pipeRuntimeWarning) fixes the issue.

**Comment by j-c-cook** [comment]
The error message shown in the original post is intermittent. I'm not sure what causes it, but it occasionally happens. I don't think I've seen it since I posted this 7 days ago. Given that I don't know how to reproduce the runtime warning, I cannot verify that your fixes have resolved the issue. My proposal is that we consider it "good enough", especially given that the runtime warnings never had an effect on results.
