### ISSUE TITLE
End length ratio 0 < alpha < 0.5

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#159]
Should the end length ratio always fall within `0 < alpha < 0.5` or only for when `nSegments==3`?

https://github.com/MassimoCimmino/pygfunction/blob/50b54afe70ac6e670b0896d0afc8561d088e2637/pygfunction/utilities.py#L55-L57

**Comment by MassimoCimmino** [comment]
That is correct. The limit `end_length_ratio < 0.5` should apply to all cases.

Also, in preparation for #159, we could consider here to allow `nSegments=2` and `nSegments=1` (which would simply return `segment_ratios=numpy.array([0.5, 0.5])` and `numpy.array([1.0])`). A warning will be required in the case `nSegments=2` to warn the user that the `end_length_ratio` parameter is overwritten.

@j-c-cook will you be working on this?

**Comment by j-c-cook** [comment]
Yes, I'll update the function and create a PR today.
