### ISSUE TITLE
Bore field from text file

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#16]
Add the option to define a bore field from an external text file, having the following structure:

```
# x   y     H     D     rb
0.    0.    100.  2.5   0.075
5.    0.    100.  2.5   0.075
0.    5.    100.  2.5   0.075
0.    10.   100.  2.5   0.075
0.    20.   100.  2.5   0.075
```

TODO:
- [ ] Implement function `boreholes.field_from_file()`
- [ ] Implement example
- [ ] Add documentation

**Comment by okolodaniel** [comment]
Hello @MassimoCimmino please is the H variable just the HORIZONTAL borehole length or do I have to factor in the buried depth (vertical U-tube) in the H value as well?

**Comment by MassimoCimmino** [comment]
Hi @okolodaniel.

`H` is the active **vertical** length of the borehole, which means the borehole transfers heat from a depth `z = D` to a depth `z = D + H`.
