### ISSUE TITLE
Deprecate outdated g-function calculation API functions

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#160]
Functions `gfunction.uniform_heat_extraction`, `gfunction.uniform_temperature`, `gfunction.equal_inlet_temperature` and `gfunction.mixed_inlet_temperature` have been kept in `v2.0` despite the introduction of the `gFunction` class.

`v2.1` will introduce a new `'equivalent'` solver which can't be implemented in a backwards compatible way due to the `use_similarities` parameter. Non-uniform discretization can still be implemented (and will be in #158).

These functions do not have any additional functionality relative to the `gFunction` class.

This issue is to introduce a deprecation warning in these functions pointing out the lack of support for the new solver and encouraging the user to use the `gFunction` class. It is proposed these functions be removed in the next major release (`v3.0`).

**Comment by j-c-cook** [comment]
I think that sounds reasonable to deprecate the older function API's, and I like that you are introducing a deprecation warning. How will `pygfunction` track upcoming deprecations? Will a `v3.0` milestone be created with a note for deprecations?

**Comment by MassimoCimmino** [comment]
That is a good point. I added a milestone but it seems only issues can be tracked. I will open an issue "Planned deprecations for v3.0" where we can keep a list.
