### ISSUE TITLE
python 3.9+ compatibility

### ISSUE THREAD

**Issue by wouterpeere** [MassimoCimmino/pygfunction#204]

**Comment by wouterpeere** [comment]
It is (for me) not possible to install the latest version of pyfunction on a python version higher than 3.9 due to problems with the coolprop package.

**Comment by j-c-cook** [comment]
Pygfunction is tested on Python==3.7 and Python==3.8. The last time I looked into building on Python==3.9 I also had errors. Perhaps this issue should address the Python version in the [Requirements](https://github.com/MassimoCimmino/pygfunction#requirements) section of the README (Document Python version requirements).  https://github.com/MassimoCimmino/pygfunction/blob/a7586fbd4237a66427d2c219d719268d2fc8feaa/.github/workflows/test.yml#L17-L18) 

Is there a package you are using that requires you to use Python 3.9, or could you use 3.7 or 3.8?

**Comment by MassimoCimmino** [comment]
Hello @wouterpeere.

CoolProp does seem to be the cause. I found that they are planning support for py39 in `v6.4.2`. There is a dev version on their [sourceforge](https://sourceforge.net/projects/coolprop/files/) which you could use in the meantime if you need py39.

I added this issue to the `v2.2` milestone. We can check if CoolProp `v6.4.2` is out once we get closer to our release.

**Comment by wouterpeere** [comment]
@j-c-cook @MassimoCimmino Thank you for your responses.

At the moment, I have no specific reason for working with a version higher than 3.8, although in the future (especially with the new, faster, python 3.11), I will be moving to a higher version.

Since I am responsible for GHEtool (https://github.com/wouterpeere/GHEtool), a tool for borefield sizing, I wanted to keep this up to date with the newer versions of python. However, GHEtool uses pygfunction for the calculation of the equivalent borehole resistance of a field, and since the latest version of pygfunction is, due to CoolProp, not available at python >=3.9, we are still using pygfunction v1.1.2 in order to assure compatibility. This is not a big problem, but it would be nice if CoolProp would release a new version so that we can rely on a newer version of pygfunction.

**Comment by MassimoCimmino** [comment]
I am removing this from the `v2.2.0` milestone. We can release a version `v2.2.x` as soon as Coolprop releases a new version that support Python 3.9+.

**Comment by MassimoCimmino** [comment]
@all-contributors please add @mitchute for code, ideas.
