### ISSUE TITLE
Create boreholes from txt file

### ISSUE THREAD

**Issue by mlfasci** [MassimoCimmino/pygfunction#220]
https://github.com/MassimoCimmino/pygfunction/blob/927a9943d261e6926eab4b59847c0731cbafd887/pygfunction/boreholes.py#L1133

Should it be if len(line) ==7 instead?

**Comment by j-c-cook** [comment]
Yes, that does appear to be a bug. I introduced the bug here: https://github.com/MassimoCimmino/pygfunction/commit/aaf2907ec46f1cc9db9497383e346a447418d01e#r78776488.

**Comment by j-c-cook** [comment]
No problem. Feel free to open up a pull request.
