### ISSUE TITLE
Publish on release workflow

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#230]
Did version 2.2.0 never get pushed onto [PyPi](https://pypi.org/project/pygfunction/#history)? Would you want to setup a [publish on release](https://github.com/j-c-cook/ghedt/blob/main/.github/workflows/python-publish.yml) workflow file? I remember thinking pre-releases don't trigger this workflow.

**Comment by MassimoCimmino** [comment]
I just published `v2.2.0`.

This issue can be used to implement the workflow. There will be some differences with ghedt since we do not have a setup.py file anymore for pygfunction.

**Comment by MassimoCimmino** [comment]
This looks like a good place to start : https://github.com/pypa/gh-action-pypi-publish

**Comment by j-c-cook** [comment]
> This is odd. I am fairly certain I uploaded it and tested the installation using pip. I will upload it today.
> 
> A workflow file would definitely streamline the release process and avoid this kind of mistake in the future.

Perhaps PyPi had to roll back a version, lost some data in the process and you were lucky enough to get in at the wrong time. A workflow can't help with that, but most of the time should reduce some of the manual input required to get a release out.
