### ISSUE TITLE
Will pygfunction drop Python version support once it reaches end of life?

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#241]
Is the plan to drop Python==3.7 upon the first release that comes after June 27, 2023? 

Here is an end of life schedule for python versions: https://endoflife.date/python.

**Comment by MassimoCimmino** [comment]
More or less. I intend to stop testing on 3.7 after that point. We haven't yet used any of the 3.8+ features so pygfunction may still be compatible with 3.7 for a while.

We update the package requirements on release and our requirements (e.g. scipy and numpy) may cause a compatibility issue if they stop supporting 3.7.

Any other recommendation?

**Comment by j-c-cook** [comment]
> More or less. I intend to stop testing on 3.7 after that point. We haven't yet used any of the 3.8+ features so pygfunction may still be compatible with 3.7 for a while.

My thought exactly. It’s not important to become incompatible with 3.7, but no harm if at some point after June 27 we do. 

> 
> We update the package requirements on release and our requirements (e.g. scipy and numpy) may cause a compatibility issue if they stop supporting 3.7.

Yes. I do remember that scipy or numpy required bumping the minimal Python version to 3.7. That may have coincided with the 3.6 end of life. 

> 
> Any other suggestion?

No. Thank you.

**Comment by j-c-cook** [comment]
I’ll close this for now. A new issue can be created in 6 months that follows up on this.
