### ISSUE TITLE
API change on patch release

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#261]
@mitchute changed the name of the first argument in `gt.media.fluid.Fluid` here: https://github.com/MassimoCimmino/pygfunction/pull/232/commits/ac88d2b39373809bc5a52694431a9c4f897a3586. 

The following code is valid for `pygfunction` version `2.2.0`, but not for version `2.2.2`. 
```
    # Fluid properties
    mixer = 'MEG'  # Ethylene glycol mixed with water
    percent = 20.  # Percentage of ethylene glycol added in
    fluid = gt.media.Fluid(mixer=mixer, percent=percent)
```

**Comment by MassimoCimmino** [comment]
I missed this change since `mixer` / `fluid_str` is not a keyword argument.

@mitchute Do you have specific requirements for the new variable name.

I would say that `fluid_str` is more appropriate than `mixer` since `mixer == 'Water'` is somewhat odd.

**Comment by j-c-cook** [comment]
Alright I'll update `ghedt` then. Please note the following functionality is functional in Python and therefore every argument can be treated as a keyword. 
```
>>> import pygfunction as gt
>>> mixer = 'MEG'
>>> percent = 20
>>> d = {'mixer': mixer, 'percent': percent}
>>> fluid = gt.media.Fluid(**d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'mixer'
>>> d = {'fluid_str': mixer, 'percent': percent}
>>> fluid = gt.media.Fluid(**d)
```
