### ISSUE TITLE
The converging value of g-function is related with the discretization scheme

### ISSUE THREAD

**Issue by metab0t** [MassimoCimmino/pygfunction#307]
I have a script to test the value of g-function when using a different number of segments and discretization schemes (uniform and non-uniform).

```python
import numpy as np
import matplotlib.pyplot as plt

import pygfunction as gt


def define_borefield(N1, N2, Bx, By):
    # Borehole dimensions
    D = 1.0  # Borehole buried depth (m)
    H = 80.0  # Borehole length (m)
    r_b = 0.10  # Borehole radius (m)

    # The field is a retangular array
    boreField = gt.boreholes.rectangle_field(N1, N2, Bx, By, H, D, r_b)

    return boreField

field = define_borefield(2, 1, 6.8, 5.7)

# Ground properties
alpha = 1.0e-6  # Ground thermal diffusivity (m2/s)

dt = 3600 * 24 * 365.0
Nt = 5
ts = [dt * Nt]

N_segs = [16, 100, 500, 1500]
gv_nonuniform = []
gv_uniform = []

for N_seg in N_segs:
    options = {
        "nSegments": N_seg,
        "disp": False,
        "approximate_FLS": True,
    }
    gf = gt.gfunction.gFunction(
        field, alpha, boundary_condition="UBWT", options=options, method="detailed"
    )
    gv = gf.evaluate_g_function(ts)
    gv_nonuniform.append(gv[-1])

    options["segment_ratios"] = np.full(N_seg, 1.0 / N_seg)
    gf = gt.gfunction.gFunction(
        field, alpha, boundary_condition="UBWT", options=options, method="detailed"
    )
    gv = gf.evaluate_g_function(ts)
    gv_uniform.append(gv[-1])

fig, ax = plt.subplots()
ax.plot(N_segs, gv_nonuniform, "o-", label="Non-uniform segments")
ax.plot(N_segs, gv_uniform, "o-", label="Uniform segments")
ax.set_xlabel("Number of segments")
ax.set_ylabel("g-function value")
ax.legend()

plt.show()
```

The output is:
![pic](https://github.com/user-attachments/assets/d9285858-7e63-4f73-baa0-e6d33c2a5a79)

The result is a little surprising because as the number of segments increase, g-function s given by non-uniform segmentation and uniform segmentation converge to different values. I wonder which value is more accurate, and should be regarded as the reference.

**Comment by metab0t** [comment]
Thanks!

The extrapolation indicates that their converging value have slight difference. Does it mean that the "exact" value of g-function depends on which discretization we use?

**Comment by MassimoCimmino** [comment]
The exact value of the g-function should be unique.

Here, I evaluated the extrapolated values using only the last three points in the increasing discretization. We should expect closer values using trend lines on log-scale graphs instead.
