### ISSUE TITLE
Infinite error loop while "Identifying similarities"

### ISSUE THREAD

**Issue by AlexLaferriere** [MassimoCimmino/pygfunction#35]
When attempting to run a whole script which doesn't have an `if __name__ == '__main__'` call, the **pygfunction.gfunction.uniform_temperature** function gets stuck in an infinite loop while undergoing the "Identifying similarities" step. This occurs on Windows with Python 2.7, both with a "normal" Python installation (Anaconda2) and with IPython. However, running line-by-line doesn't pose any problems.

If an `if __name__ == '__main__'` call is indeed used, then the problem disappears. Therefore, the following .py script will fail:

```
from__future__ import division, print_function, absolute_import
import pygfunction as gt
   
D = 4.
H = 175.
r_b = 0.075
B = 7.5
alpha = 1.0e-6
    
dt = 100*3600.
tmax = 3000. * 8760. * 3600.
Nt = 50
time = gt.utilities.time_geometric(dt, tmax, Nt)
N_1 = 1
N_2 = 1
boreField1 = gt.boreholes.rectangle_field(N_1, N_2, B, B, H, D, r_b)
gfunc = gt.gfunction.uniform_temperature(boreField1, time, alpha, disp=True)
```
while the following will work properly:
```
from __future__ import division, print_function, absolute_import
import pygfunction as gt

def main():    
    D = 4.
    H = 175.
    r_b = 0.075
    B = 7.5
    alpha = 1.0e-6
    
    dt = 100*3600.
    tmax = 3000. * 8760. * 3600.
    Nt = 50
    time = gt.utilities.time_geometric(dt, tmax, Nt)
    N_1 = 1
    N_2 = 1
    boreField1 = gt.boreholes.rectangle_field(N_1, N_2, B, B, H, D, r_b)
    gfunc = gt.gfunction.uniform_temperature(boreField1, time, alpha, disp=True)

if __name__ == '__main__':
    main()
```

**Comment by MassimoCimmino** [comment]
This seems to be a known issue with Windows and best practice (in this case, the only working option) dictates that use of multiprocessing be under `if __name__ == '__main__':`.
