### ISSUE TITLE
Coaxial pipes

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#36]
Add pipe model for coaxial pipes.

**Comment by j-c-cook** [comment]
You can add me to `Assignees` on this if you'd like. 

Due: February 28, 2021

**Comment by MassimoCimmino** [comment]
There is already a branch for this issue from 2018. I do not remember if the code was working then. The idea was to simply make use of the single U-tube class.

You can start from there if you find it useful, or obviously work on your own implementation.
