### ISSUE TITLE
Load aggregation example with multiple boreholes

### ISSUE THREAD

**Issue by jankoc** [MassimoCimmino/pygfunction#37]
It would be nice with an example with multiple boreholes using load aggregation with variable load over time where inlet and outlet temperatures are calculated for the boreholes. All examples using load aggregation currently use a single borehole, and it is not completely clear from the documentation how to proceed when using multiple boreholes. What I am looking for is an example e.g. with the following features:

Initialization:
- Set up a borehole field with e.g. 5 x 5 boreholes (boreholes.rectangle_field)
- Calculate g-functions (gfunction.uniform_temperature)
- Initialize load aggregation (LoadAgg.initialize, e.g. based on ClaessonJaved)
- Calculate pipe thermal resistance and heat transfer coefficients
- Loop over boreholes using e.g. pipes.SingleUTube

Loop over time:
- Set current load for load aggregation for each timestep (LoadAgg.set_current_load). 
- Calculate inlet temperature (get_inlet_temperature) for each timestep, and correspondingly for outlet temperature

**Comment by MassimoCimmino** [comment]
@jankoc 
You are right that an example with multiple boreholes is missing.

I have quickly set up an example with multiple boreholes on a development branch. You can find it [here](https://github.com/MassimoCimmino/pygfunction/blob/issue37_loadAggregationMultipleBoreholesExample/pygfunction/examples/fluid_temperature_multiple_boreholes.py).

Is this what you had in mind?
