### ISSUE TITLE
Documentation of functions related to Cimmino and Bernier 2014

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#54]
The uniform borehole wall temperature (UBHWT) documentation points to Cimmino and Bernier 2014. Specifically the <a href="https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/gfunction.py#L113">uniform_temperature</a> function is an implementation of Boundary Condition 3 (BC-III). Could it be placed in the documentation that it specifically applies to BC-III?

Could the documentation of the <a href="https://github.com/MassimoCimmino/pygfunction/blob/982ab6c47dae4931415f1a0f9a43bbfcfb34580c/pygfunction/gfunction.py#L14">uniform_heat_extraction</a> function point the boundary condition to which is applies from Cimmino and Bernier (2014)?

**Comment by j-c-cook** [comment]
Also should be in accordance with Cimmino (2018). 
[
![30909F14-743B-46D0-A47E-1AD90FEFA3D5](https://user-images.githubusercontent.com/39248734/103452182-208d4f00-4c92-11eb-9660-44ba7fbc4f52.jpeg)
](url)

**Comment by MassimoCimmino** [comment]
I agree, this is a good point.
