### ISSUE TITLE
Replace absolute tolerance by relative tolerance on distances in similarities method

### ISSUE THREAD

**Issue by MassimoCimmino** [MassimoCimmino/pygfunction#59]
The g-function methods use similarities to accelerate the calculation of thermal response factors (i.e. the finite line source solution) by applying the same values of thermal response factors to borehole pairs (of equal dimensions) that share similar distances, under some tolerance. At the moment the tolerance on radial distances is absolute with a default value of 10 cm. This means that distances are deemed equal if their values are within 10 cm of each other, no matter if the distance is 10 m or 100 m.

A relative tolerance (e.g. 1 %) may yield results that are as accurate much faster.

This issue is to replace the absolute tolerance on distances by a relative tolerance and validate that there is no loss in accuracy.

**Comment by j-c-cook** [comment]
By relative tolerance do you mean an adaptive tolerance based on distance? Here's a table for distance and tolerances by the way I understand the issue:

| Distance (m) | tolerance - 1% (m) | tolerance (mm) |
|--------------|--------------------|----------------|
| 1            | 0.01               | 10             |
| 10           | 0.1                | 100            |
| 100          | 1                  | 1000           |
| 1000         | 10                 | 10,000         |

Is this specifically referring to the absolute tolerance &epsilon;<sub>d,abs</sub> in `Agorithm 1: Identification of distance groups` in [Cimmino (2018)][1]?

[1]: https://okstate-stillwater.primo.exlibrisgroup.com/permalink/01OKSTATESTILL_OKSTAT/2920vv/cdi_crossref_primary_10_1080_19401493_2017_1423390

**Comment by MassimoCimmino** [comment]
Exactly.

Here is a new version of the figure of Cimmino (2018) for the comparison of steady-state values of rectangular field against the SBM method. The "analytical g-function" values are evaluated with the new tolerance.
![Figure_1](https://user-images.githubusercontent.com/23085996/103720284-0658b700-4f99-11eb-9b2b-08c747e3023b.png)

**Comment by MassimoCimmino** [comment]
This time for times -9 < ln(t/ts) < 5:

![Figure_2](https://user-images.githubusercontent.com/23085996/104056484-8f046c80-51be-11eb-9659-6ff984fcf481.png)

**Comment by MassimoCimmino** [comment]
I updated the last figure after finding an error in the generation script caused by an undocumented issue in the g-function calculations : the g-function is returned as `int` if the `time` vector is an array or a list of `int`.

I opened issue #64 to fix this issue.
