### ISSUE TITLE
Implement explicit multipole borehole resistance for double u-tube

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#73]
Add in borehole resistance calculation using Claesson and Javed (2019) for double u-tubes.

@MassimoCimmino Do you have any comments on this or how it differs from what you already have in the package? I see that you mention Cimmino (2016) in the [MultipleUTube](https://pygfunction.readthedocs.io/en/latest/pipes.html#pygfunction.pipes.MultipleUTube) class.

Due date: February 28, 2021

----------------
 Johan Claesson & Saqib Javed (2019) Explicit multipole formulas and thermal network models for calculating thermal resistances of double U-pipe borehole heat exchangers, Science and Technology for the Built Environment, 25:8, 980-992, DOI: https://doi.org/10.1080/23744731.2019.1620565

Cimmino, M. (2016). Fluid and borehole wall temperature profiles in vertical geothermal boreholes with multiple U-tubes. Renewable Energy, 96, 137–147. https://doi.org/10.1016/j.renene.2016.04.067

**Comment by MassimoCimmino** [comment]
The borehole resistances are calculated using the "full" multipole method of Claesson and Hellström (2011). The method is implemented in the [`multipole`](https://pygfunction.readthedocs.io/en/latest/pipes.html#pygfunction.pipes.multipole) function of the `pipes` module. It allows for arbitrary multipole order, number of pipes and positions.

The Claesson and Javed (2019) has limited advantages (in the context of *pygfunction*) when compared to the more general Claesson and Hellström (2011) method. It should be faster when it applies - that is for symmetrical cases and for orders 0 and 1 - and it is easier to implement. The calculated resistances are the same.

The resistances are only evaluated at initialization of the pipe objects and the overall time save should be minimal when the _g_-function calculation and the simulation itself are taken into account. There might be potential for some time savings during simulations thanks to the equivalent two-pipe geometries proposed in the paper, which should reduce the size of the systems of equations handled by the `pipe` classes.

Do you see any use for the implementation of the explicit formulas?

------------
Claesson, J., & Hellström, G. (2011). Multipole method to calculate borehole thermal resistances in a borehole heat exchanger. _HVAC&R Research_, 17(6), 895-911. DOI: 10.1080/10789669.2011.609927

**Comment by j-c-cook** [comment]
Okay thanks, that sounds good. 

Double u-tube functionality is a request that has been made for the GHE design tool _we_ are working on. (Not yet open source but I do plan to do that as soon as practical.) Moving forward I plan to depend heavily on `pygfunction`.

I don't see any need for the explicit formulas. I will be studying what you have and doing a verification process; may bolster an example or create a new one.
