### ISSUE TITLE
Fluid object with access to coolprops

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#75]
@MassimoCimmino Would you be interested in adding a `Fluid` object? Here's something I previously wrote up. 

This object takes in a fluid temperature, pressure, mixing fluid and percent mixture. The object directly accesses https://github.com/CoolProp/CoolProp to get the fluid properties. 

```
class Fluid:
    # 4/21/20
    def __init__(self, T: float = 293., P: float = 239220., mixer: str = 'MEG', percent: float = 0):
        """

        :param T: temperature of the water (Kelvin)
        :param P: pressure of the water (Pascal)
        :param mixer: the substance being mixed with water
        :param percent: the percentage of the mixture which is not water

        :example:
        >>> import OSU_ORNL_Tool as szgtl
        >>> T = 20 + 273  # Temp at 20 C for now to match GLHEPRO
        >>> gage_P = 20  # PsiG
        >>> atm_P = 14.69595
        >>> P = (gage_P + atm_P) * 6894.75728  # Pressure in Pa

        >>> # pure water
        >>> fluid = szgtl.ghe.Fluid(T=T, P=P)
        >>> print(fluid.__repr__())

        >>> # 20 % propylene glycol mixed with water
        >>> mix = 'MPG'
        >>> percent = 20
        >>> fluid = szgtl.ghe.Fluid(T=T, P=P, mixer=mix, percent=percent)

        >>> # 60% ethylene glycol mixed with water
        >>> mix = 'MEG'
        >>> percent = 60
        >>> fluid = szgtl.ghe.Fluid(T=T, P=P, mixer=mix, percent=percent)
        >>> print(fluid.__repr__() + '\n')

        >>> # 5% methanol mixed with water water
        >>> mix = 'MMA'
        >>> percent = 5
        >>> fluid = szgtl.ghe.Fluid(T=T, P=P, mixer=mix, percent=percent)
        >>> print(fluid.__repr__() + '\n')

        >>> # ethanol / water
        >>> mix = 'MEA'
        >>> percent = 10
        >>> fluid = szgtl.ghe.Fluid(T=T, P=P, mixer=mix, percent=percent)
        >>> print(fluid.__repr__() + '\n')
        """
        self.fluid_mix = 'INCOMP::' + mixer + '-' + str(percent) + '%'
        if mixer == 'MEG':
            pass
        elif mixer == 'MPG':
            pass
        elif mixer == 'MMA':
            pass
        elif mixer == 'MEA':
            pass
        # add in else if's
        else:
            warnings.warn('It is unknown whether or not cool props has the mixing fluid requested, '
                          'proceed with caution.')
        self.T = T                              # temperature of the fluid {K}
        self.P = P                              # pressure of the fluid in {Pa}
        self.rho = self.density()               # Density, {kg/m^3}
        self.mu = self.dynamic_viscosity()      # Dynamic Viscosity, {Pa s} or {N s/ m^2}
        self.nu = self.kinematic_viscosity()    # Kinematic Viscosity, {m^2/s}
        self.cp = self.mass_heat_capacity()     # Mass specific Cp Specific Heat, {J/kg/K}
        self.rhoCp = self.volumetric_heat_capacity()    # Volumetric heat capacity, {kJ/m3/K}
        self.k = self.thermal_conductivity()    # Thermal conductivity, {W/m/K}
        self.Pr = self.Prandlt_number()         # Prandlt number

    def __repr__(self):
        return str(self.__class__) + '\n' + '\n'.join(
            (str(item) + ' = ' + '{}'.format(self.__dict__[item]) for item in sorted(self.__dict__)))

    def append_to_dict(self, dnary):
        if len(list(dnary.keys())) == 0:
            for item in sorted(self.__dict__):
                dnary[item] = []
        for item in sorted(self.__dict__):
            dnary[item].append('{:.5E}'.format(self.__dict__[item]))

    def density(self):
        return PropsSI('D', 'T', self.T, 'P', self.P, self.fluid_mix)

    def dynamic_viscosity(self):
        return PropsSI('V', 'T', self.T, 'P', self.P, self.fluid_mix)

    def kinematic_viscosity(self):
        return self.mu / self.rho

    def mass_heat_capacity(self):
        return PropsSI('C', 'T', self.T, 'P', self.P, self.fluid_mix)

    def volumetric_heat_capacity(self):
        return self.rho * self.cp / 1000

    def thermal_conductivity(self):
        return PropsSI('L', 'T', self.T, 'P', self.P, self.fluid_mix)

    def Prandlt_number(self):
        return PropsSI('PRANDTL', 'T', self.T, 'P', self.P, self.fluid_mix)
```

**Comment by MassimoCimmino** [comment]
This would certainly be interesting. I was debating this a while ago and my issue was the following : If a class is implemented for the fluid, wouldn't it make sense to also have the same for grout, pipe and soil properties? Your thoughts?

**Comment by j-c-cook** [comment]
I created a pull request at #77. If you don't want to add this in I understand, but I went ahead and drafted it up in case you like it. 

Yes, I think it would make sense to use objects for the grout, pipe and soil (if we incorporate this fluid object). The grout, pipe and soil objects could all have the same object. 

We could potentially pass in a string for the `medium`, which would be ground, grout, etc. Each medium could have a different set of _required_ variables. Like the ground has an `UGT`, but none of the others have that parameter. I recommend knowing what our medium is mostly for error handling. If we were to pass a `ground` object to a function that needed to know the grounds `UGT`, we could have a method that checks that we have everything for that, ie. `ground.check_instances()` which returns True if we are good and raises error if not completely filled.

**Comment by j-c-cook** [comment]
@MassimoCimmino Given the extent of [the pipes module][1], it may not be practical to create `grout`, `pipe` and `soil` objects at this time. However, adding a fluid object would not require man hours. I am a proponent of this "quick fix" because the fluid object would provide _accessible_ fluid properties for a range of different fluid mixtures. 

With this method, we would still be passing around the individual `float` values into functions and not the object. The `fluid` objects main purpose would be to retrieve properties from `coolprops`; not necessarily be passed into functions (yet or maybe never). 

The other option would be to leave the fluid property determination up to an external `ground heat exchanger design tool`.  

Up to you. 

[1]: https://github.com/MassimoCimmino/pygfunction/blob/584754b86234ad4b516618813971548741eec339/pygfunction/pipes.py

**Comment by MassimoCimmino** [comment]
Ok, I agree. I will include this in the v2.0 milestone. Since we have to rework some examples, might as well make use of the new fluid class.

**Comment by j-c-cook** [comment]
`media` module doesn't appear in the documentation. I checked the files and it looks like we had done everything. Not sure what the problem is. Can you see the `media` module in the [docs](https://pygfunction.readthedocs.io/en/latest/modules.html)? @MassimoCimmino

**Comment by MassimoCimmino** [comment]
@j-c-cook #86.
