### ISSUE TITLE
Effective borehole resistance reference 

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#80]
The function that computes the `effective borehole thermal resistance` does not have a citation. Does this come from the literature somewhere?

https://github.com/MassimoCimmino/pygfunction/blob/584754b86234ad4b516618813971548741eec339/pygfunction/pipes.py#L1850-L1880

**Comment by MassimoCimmino** [comment]
This comes from the definition of the effective borehole thermal resistance for a uniform borehole wall temperature:
`R_b_eff = (T_b - T_f)/(Q_b/H)`, with `T_f = 0.5*(T_in + T_out)`

The pipe coefficients give:
`T_out = a_out*T_in + [b_out]*[T_b]`, with `[T_b]` a vector of segment temperatures.
and
`[Q_b] = [a_Q]*T_in + [b_Q]*[T_b]`, with `[Q_b]` a vector of segment heat extraction rates (in Watts)

Using only one segment along the borehole and with `T_b=0`, we get:
`T_out = a_out*T_in` and `Q_b = a_Q*T_in` (all variables are scalars)
so:
`R_b_eff = (T_b - T_f)/(Q_b/H) = -0.5*(T_in + a_out*T_in)/(a_Q*T_in/H) = -0.5*(1 + a_out)/(a_Q/H)`

This way of calculating the resistance was introduced in [1].

-------------
[1] Massimo Cimmino (2019) Semi-Analytical Method for g-Function Calculation of bore fields with series- and parallel-connected boreholes, Science and Technology for the Built Environment, 25:8, 1007-1022, DOI: 10.1080/23744731.2019.1622937

**Comment by j-c-cook** [comment]
I have compared effective borehole thermal resistance calculations for single U-tubes across different programs. The mass flow rate was varied to cover a range of Reynolds numbers and the comparison is in the plot below. The legend contains calculations from the ground loop heat exchanger design tool (GLHEDT) and Ground Loop Heat Exchanger Professional (GLHEPRO). GLHEDT has the ability to call one of two methods: C++ code from EnergyPlus (E+) that has been wrapped via Cython and made available to pure python, and pygfunction's (pyg) calculation. 

Have you done similar comparisons to the one I share? What are your thoughts? 

![single_u-tube](https://user-images.githubusercontent.com/39248734/128534171-414b9434-fe33-4244-bf4c-7e4d555482b9.jpg)

**Comment by j-c-cook** [comment]
Could you confirm that the mass flow rate input to the effective borehole resistance calculation is supposed to be `m_flow_borehole` and not `m_flow_pipe`?

https://github.com/MassimoCimmino/pygfunction/blob/7d37b8b3bf4b349701681e42281c21cccb54ca42/pygfunction/pipes.py#L1898-L1928

**Comment by MassimoCimmino** [comment]
Yes, it is meant to be the inlet mass flow rate into the borehole. For a double U-tube, we have `m_flow_borehole = 2*m_flow_pipe`.
