### ISSUE TITLE
Contributing Standards - Git Commit Messages

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#83]
We have contributing standards detailed in [CONTRIBUTING.md](https://github.com/MassimoCimmino/pygfunction/blob/master/CONTRIBUTING.md). 

Perhaps we should also request that a standard be followed for [commit messages](https://gist.github.com/turbo/efb8d57c145e00dc38907f9526b60f17)?

**Comment by j-c-cook** [comment]
If you use `nano`, then you can set an option to constantly show the column you are in https://askubuntu.com/a/73465/1102016.

When typing `git help commit | grep -C 1 50` into terminal, the following message is displayed (https://stackoverflow.com/a/56887076/11637415):
```
DISCUSSION
       Though not required, it’s a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a blank line
       and then a more thorough description. The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git.
```

[Torvalds](https://github.com/torvalds/linux/pull/17#issuecomment-5661185) addresses the 50/72 rule here.

**Comment by MassimoCimmino** [comment]
This is a good ideal to strive for. I will not argue against Torvalds. This style is certainly objectively better.

Where I am having issues is that *pygfunction* is not strictly a software development project where we can expect interested contributors to follow good practices in all aspects of coding, documentation, and version control. The bar is already pretty high with regards to the scientific/engineering knowledge required to contribute to the project, and adding this kind of contributing standard may scare some.

With that in mind, gathering up resources for interested contributors to learn and/or apply good practices while contributing is definitely a good addition to the contributing standards. I, for one, am definitely looking forward to improve on this aspect.

**Comment by j-c-cook** [comment]
I’m going to close this as the contributing file is plenty for getting started here. Anything past that can be left to the individual.
