### ISSUE TITLE
Reduce segment responses held in memory

### ISSUE THREAD

**Issue by j-c-cook** [MassimoCimmino/pygfunction#85]
The segment response matrix [h_ij](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L203) is of size `nq x nq x nt`, where `nq` is the number of sources in the field, and `nt` is the number of time steps. 

Two variants of the segment response matrix [h_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L228) and [dh_ij](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L232) are computed. The factor increment matrix `dh_ij` is used in calculating the borehole wall temperatures based on all previous responses, equation 18 from Cimmino (2018). The `h_dt` matrix sets up the linear interpolation for the current thermal response factor matrix [h_ij_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L241), and can be seen in equation 18 in Cimmino (2018). 

With the current methodology here, the segment response matrix `h_ij` is necessary for computing both `h_dt` and `dh_ij`. Therefore, it is not directly possible to get around _having_ to hold `3 (nq x nq x nt)` segment response factors in memory. With each of the segment responses being double precision (at 16 bytes). 

Would it be possible to directly compute [h_ij_dt](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L241) and [dh_ij[:, :, t]](https://github.com/MassimoCimmino/pygfunction/blob/d48f31099b56e731a4ca5a0998268c1c94ba4602/pygfunction/gfunction.py#L768) from `h_ij` without computing `dh_ij` and `h_dt` without losing speed performance? 

-----------------------

Massimo Cimmino (2018) Fast calculation of the g-functions of geothermal borehole fields using similarities in the evaluation of the finite line source solution, Journal of Building Performance Simulation, 11:6, 655-668.

**Comment by MassimoCimmino** [comment]
Can you take a look at the new implementation in #33 ? I discovered while working on this that the `interp1d` stored a copy of `h_ij` by default as `h_ij.y`. The new implementation uses this and computes `h_dt` once per time step (its size is now `nq x nq`).

------------------

`Similarities.thermal_response_factors()` returns an `interp1d` object with a stored copy of `h_ij`.

https://github.com/MassimoCimmino/pygfunction/blob/8b5bc09ce4d4659cda19d5a81ff158decfdd56ff/pygfunction/gfunction.py#L1436-L1443

https://github.com/MassimoCimmino/pygfunction/blob/8b5bc09ce4d4659cda19d5a81ff158decfdd56ff/pygfunction/gfunction.py#L844

The matrix `h_dt` is now calculated one timestep at a time. This could potentially slow down calculations.

https://github.com/MassimoCimmino/pygfunction/blob/8b5bc09ce4d4659cda19d5a81ff158decfdd56ff/pygfunction/gfunction.py#L867-L873

**Comment by j-c-cook** [comment]
Really nice discovery about `interp1d`, that helps. 

Issue #33 was initially proposed as a `Refactor` (at least that's what I was focused on back in December 2020), your additional work could now classify it as `Optimize-Refactor`. This will reduce the memory consumption by `2 * (nq x nq x nt) * 16` bytes. For a field with 400 boreholes at 12 segments per borehole, there will be about 11 GB less memory consumed.   

An acceptance of pull request #84 will merge this into `master` and will be released in [v2.0.0](https://github.com/MassimoCimmino/pygfunction/milestone/4).

I'll run `memory` and `time` tests on this when I get the chance. I believe time difference will be negligible.

**Comment by MassimoCimmino** [comment]
If this is to be tied to #84, we can consider adding a `dtype` option to the `gFunction`class. By default, all numpy arrays are initialized as `np.float64` (double precision). I have successfully evaluated the g-function of fields of >1000 boreholes by bringing the precision down to `np.float16` (half-precision). I have not tested the consequences on the accuracy.

Is there a need for this feature?

**Comment by j-c-cook** [comment]
```
numpy.half         16-bit-precision
numpy.single      32-bit-precision
numpy.double    64-bit-precision
```
I think an optional argument for the precision would be a good feature. The lowest precision with _acceptable_ accuracy could be default. An input will allow for the consequences of accuracy to be more easily tested.

**Comment by MassimoCimmino** [comment]
There is an argument to make to keep the default `np.double` according to numpy standards since this is the data type expected by the average user. *Acceptable accuracy* is subjective and dependent on the application. Decreasing the precision should only be relevant when memory is an issue (calculation time should not be affected).

There is also `numpy.longdouble`.

**Comment by j-c-cook** [comment]
I agree that it makes sense for the default optional `dtype` argument to be `np.double`  in the `gFunction` class. Thanks for a0f78b162c4c0a3741448813a9e4ceb066e95705.

**Comment by MassimoCimmino** [comment]
numpy data types are the subject of [NEP40](https://numpy.org/neps/nep-0040-legacy-datatype-impl.html#nep40). This may have future repercussions on the `dtype` feature. Something to keep in mind.
