### ISSUE TITLE
Problem with pip install

### ISSUE THREAD

**Issue by pmcmm** [MassimoCimmino/pygfunction#92]
Hello everyone, I'm just getting started looking at this excellent piece of work. It looks promising! 

I found some minor issues while playing around with the example scripts. I am using anaconda as the package manager for python libraries, and I installed this library through pip install. However there seems to be a problem with the media.py library, it is missing (see screenshot below). 

![image](https://user-images.githubusercontent.com/12100722/116064382-3fbb4c80-a686-11eb-9da9-938715ef6969.png)

Trying to solve it, I added manually the missing file to the folder by taking it out directly from the repo, but then I get an error when trying to import the library. This is the error line:

`from CoolProp.CoolProp import PropsSI`

So I couldn't solve the issue and I can't get the media library up and running.

**Comment by MassimoCimmino** [comment]
Hello @pmcmm. Thank you for the good words.

The `pip install` command installs the latest official release, in this case [v1.1.2](https://github.com/MassimoCimmino/pygfunction/releases/tag/v1.1.2), dated Jan 22, 2021. The `media` module will be part of the next major release (v2.0.0) *very soon*.

There is always the possibility of installing the current state of pygfunction on the `master` branch by clcking on the green "Code" button on the main page. You can then run the installation script on the Anaconda Prompt (in administrator mode, if you are using windows), as shown on the main page. Coolprop is part of the requirements, so it should be automatically installed when running the script. If not, you can also install it manually using `pip install Coolprop`.

**Comment by pmcmm** [comment]
@MassimoCimmino, thanks for the quick reply!

Yes, I can imagine that copying the entire repo would also work, but the point of the pip install is to simplify that process :) 

as the documentation shows support for pip installation, I just found useful to report my findings, but it turns out you are already aware of it, so never mind my issue. I can now go back to play around with your tool :)
